// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/code/test/dklStaticSite/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.7_@types+node@20.5.1_eslint@8.56.0_prettier@2.8.8_react-dom@18.2_jrput5psj2bktgt7f7xjgt4mqy/node_modules/dumi/theme-default/slots/HeaderExtra/index.js';
