// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { getSketchJSON } from 'D:/code/test/dklStaticSite/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/code/test/dklStaticSite/node_modules/.pnpm/@umijs+renderer-react@4.0.90_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type { History } from 'D:/code/test/dklStaticSite/node_modules/.pnpm/@umijs+renderer-react@4.0.90_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/code/test/dklStaticSite/node_modules/.pnpm/umi@4.0.90_@babel+core@7.23.7_@types+node@20.5.1_eslint@8.56.0_prettier@2.8.8_react-dom@18.2._55qstgsxmt4o627kt3372kd3ku/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
