name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install and Build
        run: 
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          github_token: ${{ secrets.DINGKAILE_DEPLOY }}